Upload to bs using fastlane for android

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -163,28 +163,32 @@ jobs:
           command: bundle update fastlane 
 
       - run:
-          name: Fastlane
+          name: Fastlane build
           command: bundle exec fastlane $FASTLANE_LANE
 
       - store_artifacts:
           path: app/build/outputs/apk/release/app-release.apk
 
       - run:
-          name: App upload and Set app id in environment variable.
-          command: |
-            APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/Users/distiller/react-native-stock-price-app/android/app/build/outputs/apk/release/app-release.apk")
-            echo "APP_UPLOAD_RESPONSE :  " + $APP_UPLOAD_RESPONSE
-            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
-            if [ $APP_ID != null ]; then
-              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
-              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
-              source $BASH_ENV;
-              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
-            else
-              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
-              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
-              exit 1;
-            fi
+          name: Fastlane upload test
+          command: bundle exec fastlane upload_test
+
+      # - run:
+      #     name: App upload and Set app id in environment variable.
+      #     command: |
+      #       APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/Users/distiller/react-native-stock-price-app/android/app/build/outputs/apk/release/app-release.apk")
+      #       echo "APP_UPLOAD_RESPONSE :  " + $APP_UPLOAD_RESPONSE
+      #       APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+      #       if [ $APP_ID != null ]; then
+      #         echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+      #         echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+      #         source $BASH_ENV;
+      #         echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+      #       else
+      #         UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+      #         echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+      #         exit 1;
+      #       fi
 
       - run:
           name: Run the metro server
