build android with fastlane

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,7 +42,7 @@ jobs:
       - store_artifacts:
           path: reporter
 
-  macos-build-and-test:
+  ios-build-and-test:
     working_directory: ~/react-native-stock-price-app
     macos:
       xcode: 13.2.1
@@ -56,7 +56,7 @@ jobs:
       - run: cd $PLATFORM;bundle install
       - run: cd $PLATFORM; bundle exec fastlane $FASTLANE_LANE
       - store_artifacts:
-          path: ios/output
+          path: $PLATFORM/output
           destination: ipa
     
       - store_artifacts:
@@ -79,18 +79,54 @@ jobs:
               exit 1;
             fi
 
+  android-build-and-test:
+    working_directory: ~/react-native-stock-price-app
+    macos:
+      xcode: 13.2.1
+    environment:
+      FL_OUTPUT_DIR: output
+      FASTLANE_LANE: beta_release
+      PLATFORM: android
+    shell: /bin/bash --login -o pipefail
+    steps:
+      - checkout
+      - run: cd $PLATFORM;bundle install
+      - run: cd $PLATFORM; bundle exec fastlane $FASTLANE_LANE
+      - store_artifacts:
+          path: $PLATFORM/output
+          destination: apk
+    
+      - store_artifacts:
+          path: $PLATFORM/$FL_OUTPUT_DIR
+
+      - run:
+          name: App upload and Set app id in environment variable.
+          command: |
+            APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@react-native-stock-price-app/android/app/build/outputs/apk/debug/app-debug.apk")
+            echo "APP_UPLOAD_RESPONSE :  " + $APP_UPLOAD_RESPONSE
+            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+            if [ $APP_ID != null ]; then
+              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
+              source $BASH_ENV;
+              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+            else
+              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+              exit 1;
+            fi
 
 
 workflows:
   node-android-ios:
     jobs:
       - node
-      # - android-build-and-test:
-      #     context:
-      #       - BROWSERSTACK_CREDENTIALS
-      #     requires:
-      #       - node
-      - macos-build-and-test:
+      - android-build-and-test:
+          context:
+            - BROWSERSTACK_CREDENTIALS
           requires:
             - node
+      # - ios-build-and-test:
+      #     requires:
+      #       - node
 
